# numpy practice session

In [1]:
import numpy as np


# creating an array 

In [3]:
food=np.array(["pakora", "samosa", "raita"])
food

array(['pakora', 'samosa', 'raita'], dtype='<U6')

In [4]:
prices = np.array([5,5,5])
prices

array([5, 5, 5])

In [5]:
type(prices)

numpy.ndarray

In [6]:
type(food)

numpy.ndarray

In [9]:
len(food)

3

In [13]:
prices[2]

5

In [14]:
prices[0:]

array([5, 5, 5])

In [15]:
food[1]

'samosa'

In [17]:
prices.mean()

5.0

In [18]:
# zeros
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [19]:
# ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [20]:
#np.empty ##assignments why 1
np.empty(5)

array([1., 1., 1., 1., 1.])

In [22]:
#ranges
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
#specify
np.arange(2-20) #why this

array([], dtype=int32)

In [24]:
#specify
np.arange(2,20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [25]:
#specific interval
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [27]:
#table
np.arange(5,50, 5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [32]:
# line space
np.linspace(0,10, num=4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [37]:
#specify data type
np.ones(50, dtype=np.int64)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1], dtype=int64)

In [38]:
#specify data type
np.ones(50, dtype=np.float64)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# aray function


In [39]:
a =np.array([10,12,15,2,4,6,100,320,0.5,10.3])
a

array([ 10. ,  12. ,  15. ,   2. ,   4. ,   6. , 100. , 320. ,   0.5,
        10.3])

In [40]:
a.sort()
a

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
       320. ])

In [41]:
b = np.array([10.2,95.6,91,67.7])
b

array([10.2, 95.6, 91. , 67.7])

In [45]:
c=np.concatenate((a,b))
c

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
       320. ,  10.2,  95.6,  91. ,  67.7])

In [46]:
c.sort()
c

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.2,  10.3,  12. ,  15. ,
        67.7,  91. ,  95.6, 100. , 320. ])

# 2-D array

In [61]:
a= np.array([[1,2],[5,4]])  ##read code 15,16
a

array([[1, 2],
       [5, 4]])

In [62]:
b= np.array([[6,7],[8,9]])
b

array([[6, 7],
       [8, 9]])

In [64]:
np.concatenate((a,b), axis=0)

array([[1, 2],
       [5, 4],
       [6, 7],
       [8, 9]])

In [65]:
np.concatenate((a,b), axis=1)

array([[1, 2, 6, 7],
       [5, 4, 8, 9]])

In [66]:
# 2d array with some functions (tensor)
a= np.array([[[0,1,2,3],
             [4,5,6,7]],
             [[0,1,2,3],
             [4,5,6,7]],
             [[0,1,2,3],
             [4,5,6,7]]])
a

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [73]:
type(a)

numpy.ndarray

In [68]:
# to find nmbr of dimension
a.ndim

3

In [71]:
b=np.array([[5,6,7],
          [8,9,10],
           [11,12,13]])
b

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [72]:
b.ndim

2

In [74]:
# size/number of element
a.size

24

In [76]:
a

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [75]:
# shape
a.shape

(3, 2, 4)

In [99]:
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [102]:
# reshape
a= a.reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [105]:
# new shape
# import numpy as np
np.reshpae(a, newshape=(1, 9), order='c')

AttributeError: module 'numpy' has no attribute 'reshpae'

In [107]:
#conver 1 d into 2d
a= np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [108]:
a.shape

(9,)

In [109]:
#rowwise
b= a[np.newaxis, :]
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [110]:
b.shape

(1, 9)

In [111]:
# column wise
c= a[:, np.newaxis]
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [112]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [114]:
a[2:9]

array([3, 4, 5, 6, 7, 8, 9])

In [115]:
a*6

array([ 6, 12, 18, 24, 30, 36, 42, 48, 54])

In [116]:
a+6

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15])

In [117]:
a.sum()

45

In [118]:
a.mean()

5.0